### ISSUE TITLE
Hostpot very slow

### ISSUE THREAD

**Issue by ManuelCostanzo** [maccuaa/asus-ac53-rtl8822bu#2]
Hello, i successful installed two TPLINK T4U AC 1300, in  two different computers. I created a hostpot in one computer and the  other is connected to it. My problem is that when i test the speed using  iperf3, the maximum value that i obtain is 13MB/S. I switch to  different channels, different bands (2.4 GHz and 5GHz), but changes were  worst, i have never got more than 13MB/S. Please, i need some help to solving this. Thank you very much.
--

**Comment by maccuaa** [comment]
I'm neither the manufacturer of the device nor the author of the driver so I can't help you unfortunately.

Please reach out to Asus for any technical support questions you may have. I am in no way affiliated with Asus.
