### ISSUE TITLE
how to add it in dkms?

### ISSUE THREAD

**Issue by tester1969** [maccuaa/asus-ac53-rtl8822bu#3]
this

**Comment by maccuaa** [comment]
https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support

**Comment by maccuaa** [comment]
@tester1969 I tried adding DKMS support a couple weeks ago but couldn't figure it out. If you managed to get it working then post the instructions here or open a PR and i'll get it added to this repo.

**Comment by tester1969** [comment]
Did half the road. Somehow it doesn't rebuild auto when a new kernel is installed. I changed some things and i will wait next kernel update to check

**Comment by tester1969** [comment]
Hello, create the dkms.conf with the following data:

dkms.conf
```
PACKAGE_NAME="rtl88x2bu"
PACKAGE_VERSION="5.3.1"
BUILT_MODULE_NAME="88x2bu"
DEST_MODULE_LOCATION="/kernel/drivers/net/wireless/"
REMAKE_INITRD="yes"
AUTOINSTALL="yes"
MAKE="'make' all KVER=${kernelver}"
CLEAN="make clean"
```

and put the file in your root directory (the same directory that has the Makefile). Then issue:

```
$ dkms add -m 88x2bu -v 5.3.1
```

This should copy also the source files to `/var/lib/dkms/rtl88x2bu/5.3.1/source`. If not copy them yourself.

```
$ dkms build -m 88x2bu -v 5.3.1
$ dkms install -m 88x2bu -v 5.3.1
```

After that point with any upgrade this should compile the new module and put it in initrd.
I have only a fedora, so I can't test on other flavors
Cheers

**Comment by maccuaa** [comment]
Awesome, thanks @tester1969! I'll give that a shot sometime this week.

**Comment by tester1969** [comment]
Just a small note. You must be root to run the commands, or sudo them
