### ISSUE TITLE
Driver disappears after restarting - Ubuntu 20.04

### ISSUE THREAD

**Issue by ntekniklaus** [maccuaa/asus-ac53-rtl8822bu#5]
After following instructions to compile and add to the kernel, the driver worked with the AC53 just fine. However, after restart, it just acted as if it never happened. Going to the wifi menu in Ubuntu just shows that there's no devices attached.
If you need any more info let me know and I'll put it here.

**Comment by maccuaa** [comment]
Not sure if there's something that you have to do differently for Ubuntu. I found this StackOverflow question, does this work for you? 

https://askubuntu.com/questions/90067/how-do-i-get-my-wireless-to-automatically-start-after-reboot

**Comment by ntekniklaus** [comment]
Awesome! It worked! Thank you. If you don't mind, I feel you should add running that command to the instructions if you can.

**Comment by maccuaa** [comment]
@ntekniklaus what commands did you run exactly to resolve the issue? I'll update the README or see if i can do it automatically in the build script.

**Comment by ntekniklaus** [comment]
Ran sudo modprobe 88x2bu.ko, also put 88x2bu.ko in /etc/modules and it worked on startup after that.
